### PR TITLE
Move "concourse" namespace creation in separate script

### PR DESCRIPTION
**Pull request by jochenehret**
* we need the ns before running "deploy" to store the github credentials as secrets

Signed-off-by: Aftab Alam <81828613+iaftab-alam@users.noreply.github.com@sap.com>

### CODE REVIEW

**Comment by jochenehret** [comment]
Note: We will update the README after https://github.com/cloudfoundry/bosh-community-stemcell-ci-infra/pull/51 has been merged to avoid merge conflicts.

**Review by ramonskie — APPROVED** [review]
makes sense
but we should still check if namespace is set in deploy script.
to prevent mistakes

**Review by ramonskie — CHANGES_REQUESTED** [review]
we should still check if namespace is set correctly in deploy script

**Review by rkoster — APPROVED** [review]
LGTM

**Comment by rkoster** [comment]
Thanks! @jochenehret

**Pull request merged**
